-- Enable DBMS_OUTPUT for feedback
SET SERVEROUTPUT ON;

-- Step 1: Truncate All Tables in Correct Order to Avoid Foreign Key Constraints
BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE ORDER_DETAILS';
    DBMS_OUTPUT.PUT_LINE('Table ORDER_DETAILS truncated successfully.');

    EXECUTE IMMEDIATE 'TRUNCATE TABLE CUSTOMER_ORDER';
    DBMS_OUTPUT.PUT_LINE('Table CUSTOMER_ORDER truncated successfully.');

    EXECUTE IMMEDIATE 'TRUNCATE TABLE INVENTORY_TRANSFER';
    DBMS_OUTPUT.PUT_LINE('Table INVENTORY_TRANSFER truncated successfully.');

    EXECUTE IMMEDIATE 'TRUNCATE TABLE WAREHOUSE_PRODUCT';
    DBMS_OUTPUT.PUT_LINE('Table WAREHOUSE_PRODUCT truncated successfully.');

    EXECUTE IMMEDIATE 'TRUNCATE TABLE SUPPLIER_PRODUCT';
    DBMS_OUTPUT.PUT_LINE('Table SUPPLIER_PRODUCT truncated successfully.');

    EXECUTE IMMEDIATE 'TRUNCATE TABLE CUSTOMER';
    DBMS_OUTPUT.PUT_LINE('Table CUSTOMER truncated successfully.');

    EXECUTE IMMEDIATE 'TRUNCATE TABLE WAREHOUSE';
    DBMS_OUTPUT.PUT_LINE('Table WAREHOUSE truncated successfully.');

    EXECUTE IMMEDIATE 'TRUNCATE TABLE PRODUCT';
    DBMS_OUTPUT.PUT_LINE('Table PRODUCT truncated successfully.');

    EXECUTE IMMEDIATE 'TRUNCATE TABLE SUPPLIER';
    DBMS_OUTPUT.PUT_LINE('Table SUPPLIER truncated successfully.');
END;
/

